name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List files for debugging
      run: |
        echo "=== Production Deployment Files ==="
        ls -la
        find . -name "*.html" -o -name "*.css" -o -name "*.js"
        
    - name: Deploy to Production via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./
        exclude: |
          .git/**
          .github/**
          README.md
          SETUP.md
          PROJECT-STATUS.md
          .gitignore
