name: Deploy to Production (tabell.top)

on:
  push:
    branches: [ main ]
  # Trigger from tabell-dev repository via workflow_dispatch
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (should be tabell-dev)'
        required: false
        default: 'tabell-dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (if needed for build)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm install
        fi
        
    - name: Build project (if build script exists)
      run: |
        if [ -f package.json ] && npm run build --if-present; then
          echo "Build completed"
        fi
    
    - name: Deploy to Production Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PROD_FTP_SERVER }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
          README.md
          package.json
          package-lock.json
          .gitignore